### ISSUE TITLE
Questions about some details of Chinese sign language dataset.

### ISSUE THREAD

**Issue by jiuriH** [Tiantiansayhi/Robust-Real-time-Motion-Retargeting-via-Neural-Latent-Prediction#1]
Thanks for your great work. I solved many problems,and read the Chinese sign language dataset. 

In the h5 file of that, there are several groups, which may represent different sign language action sequences. Each group is composed of 17 datasets. These datasets may be the pose and rotation angle of the human arm。

It's not clear to me whether each dataset (e.g. **"l_fr_pos"**, "**l_fr_quat**", "**r_up_pos**", "**r_up_quat**")in a group represents the pose and rotation of a rigid body in the human arm, or the pose and rotation of certain key points in the human arm. And how rigid bodies or key points are modeled.

If possible, hoping to communicate more with you. I am a student from USTC,China. My email is hanxujun@mail.ustc.edu.cn and wechat is hxj2601. Looking forward to your reply!

**Comment by Tiantiansayhi** [comment]
I'm sorry for taking so long to reply you. I haven't read the issue before.
In the H5 files, the data is obtained by using motion caption from a Chinese language teacher.
let me explain the meaning of these data:
We use two kinds of data, one for arm of person and one for hands of person. you can find the process of dealing with the original data in **database.py** in multi-retaregting branch.
**glove data** contains **l_glove_angle** and **r_glove_angle** mean left and right hand data for each joints.
**arm data** contains:
**l_up_pos** and **r_up_pos** mean left and right shoulder position in Cartesian space;
**l_fr_pos** and **r_fr_pos** mean left and right elbow position in Cartesian space;
 **l_hd_pos** and **r_hd_pos** mean left and right wrist position in Cartesian space.
And the quaternion data you can inference as before.
I am not sure if this is clear. Hope this will help you.

**Comment by jiuriH** [comment]
Thanks for your reply! 
Your outstanding work really gives me a lot of inspiration.
By the way, do you think it's possible to use your method in real world experiments?
I am trying to obtain the pose data of the human arm and hand in a visual manner, in the same format as in your dataset. Then do some real world experiments.

**Comment by Tiantiansayhi** [comment]
For motion sequence retaregting part, i think it can realize in real world, because some experiments in real world based on single motion retargeting were evaluated.
For sequence prediction, i think the real experimental result depends on the hardware, the more time spend on hardware, the results for prediction are better. And also it influenced the accuracy of prediction.
But you can try it in real world, and I also hope it can have a good influence on your research.

**Comment by jiuriH** [comment]
Thank you for your insights! 
I appreciate your thoughts on the motion sequence retargeting and sequence prediction. 
I’ll give it a try!
